
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: sapcon-terminal
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Serial Port Terminal with easy presets # 79 char long summary
  description: |
   Easy to use Serial Port Terminal APP
   After install 
   give the user dialout permissions

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  base: core20
  
  apps:
    sapcon-terminal:
      extensions:
        - kde-neon
      command: sapcon-terminal
  architectures: [amd64, arm64, armhf]

  parts:
    sapcon-terminal:
      # See 'snapcraft plugins'
      plugin: cmake
      cmake-parameters:
          - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
          - "-DCMAKE_PREFIX_PATH=/usr"
          - "-DCMAKE_BUILD_TYPE=Release"
          - "-DENABLE_TESTING=OFF"
          - "-DBUILD_TESTING=OFF"
    
      source-type: git
      source-branch: master
      source: https://github.com/djpalshikar/sapcon-terminal
  
  
    
